### ISSUE TITLE
Validator rank is incorrectly exported for some chains

### ISSUE THREAD

**Issue by bombermine3** [QuokkaStake/cosmos-validators-exporter#84]
For example:
deNodes validator is ranked 11th by VP https://testnet.junction.explorers.guru/validators
But in the metrics, it is ranked 6th.

```
# HELP cosmos_validators_exporter_rank Rank of a validator compared to other validators on chain.
# TYPE cosmos_validators_exporter_rank gauge
cosmos_validators_exporter_rank{address="airvaloper1fjyv285xffmn26jtwaz24d5ysmqlprzxlhxgag",chain="airchains"} 6
```

**Comment by freak12techno** [comment]
Interesting, I'll take a look, thanks for reporting?
Can you share the chain config to make it easier to debug?

**Comment by bombermine3** [comment]
```
timeout = 10
listen-address = ":9560"

[log]
level = "info"
json = false

[[chains]]
name = "airchains"
lcd-endpoint = "http://localhost:1317"
base-denom = "uamf"
denoms = [
    { denom = "uamf", display-denom = "amf", denom-exponent = 6, ignore = false },
]
bech-wallet-prefix = "air"
validators = [
    { address = "airvaloper1fjyv285xffmn26jtwaz24d5ysmqlprzxlhxgag", consensus-address = "airvalcons1q6sc2ggdyxvu709yxnxflqvvqwf7npk5lws4ua" }
]
is-provider = false

[chains.queries]
delegations = true
unbonds = true
self-delegation = true
validators = true
consumer-validators = true
consumer-info = true
commission = true
rewards = true
balance = true
assigned-key = true
signing-info = true
slashing-params = true
params = true
staking-params = true
node-info = true
```

And here is the public API for testing: https://airchains-junction-api.denodes.xyz

**Comment by freak12techno** [comment]
@bombermine3 tried this, your node seems to time out. are there any other nodes I can test it on?

**Comment by bombermine3** [comment]
I forgot to remove the rate limit I set recently. Please try again

**Comment by freak12techno** [comment]
okay that didn't help, but apparently the issue wasn't the rate limit, but rather probably my location - using VPN helped. wonder if Russian IPs are blocked or something.
regardless, I've found the bug, it was due to the pagination and my assumption that there won't be more than 1000 validators while there's 1455 so far - will fix in a bit.

**Comment by freak12techno** [comment]
@bombermine3 okay I just released v7.0.1 that should fix it, can you verify?

**Comment by bombermine3** [comment]
I think access to Hetzner is being blocked from Russia by some providers, unfortunately.

As for this issue, it has been fixed for Airchains but still persists for Fairblock and Sunrise chains.

Fairblock:
Actual rank: 15
Exported rank: 4
https://testnet-api.fairblock.network/

```
timeout = 10
listen-address = ":9560"

[log]
level = "info"
json = false

[[chains]]
name = "fairblock"
lcd-endpoint = "http://localhost:1317"
base-denom = "ufairy"
denoms = [
    { denom = "ufairy", display-denom = "fairy", denom-exponent = 6, ignore = false },
]
bech-wallet-prefix = "fairy"
validators = [
    { address = "fairyvaloper1vqdjp6vw6r9uszn8elqyzwa9p5cyppdplwfmqk", consensus-address = "fairyvalcons1u3cjngcetfwy88tufgrsummtx8nhyyjrkzr32n" }
]
is-provider = false

[chains.queries]
delegations = true
unbonds = true
self-delegation = true
validators = true
consumer-validators = true
consumer-info = true
commission = true
rewards = true
balance = true
assigned-key = true
signing-info = true
slashing-params = true
params = true
staking-params = true
node-info = true
```

Sunrise:
Actual rank: 5
Exported rank: 6
https://sunrise-testnet-0x-api.denodes.xyz/

```
timeout = 10
listen-address = ":9560"

[log]
level = "info"
json = false

[[chains]]
name = "sunrise"
lcd-endpoint = "http://localhost:1317"
base-denom = "uvrise"
denoms = [
    { denom = "uvrise", display-denom = "vrise", denom-exponent = 6, ignore = false },
]
bech-wallet-prefix = "sunrise"
validators = [
    { address = "sunrisevaloper1dzuvf3dd83csf9d5wyqwl5evkxe6fwk486gypd", consensus-address = "sunrisevalcons1g0p6vnrhpjjfh0vjjh4gc5xe9tudfv6cdjvme6" }
]
is-provider = false

[chains.queries]
delegations = true
unbonds = true
self-delegation = true
validators = true
consumer-validators = true
consumer-info = true
commission = true
rewards = true
balance = true
assigned-key = true
signing-info = true
slashing-params = true
params = true
staking-params = true
node-info = true
```

**Comment by freak12techno** [comment]
@bombermine3 can you build from this PR https://github.com/QuokkaStake/cosmos-validators-exporter/pull/86 and check if it's behaving correctly? think I fixed it, but better check twice.

**Comment by bombermine3** [comment]
Now it works perfectly. Thank you!

**Comment by freak12techno** [comment]
Okay I'll release 7.0.2 in a few minutes then. Thanks!

**Comment by freak12techno** [comment]
7.0.2 is fixed, so closing this now as resolved. Let me know if there are more issues, and thanks for reporting!
